name: Build Tailwind CSS

on:
  push:
    paths:
      - 'input.css'
      - '**.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-tailwind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tailwind CLI
        run: npm install --no-save @tailwindcss/cli

      - name: Build Tailwind CSS
        run: npx tailwindcss -i input.css -o ./static/style.css --minify

      - name: Commit and Push compiled CSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static/style.css
          git commit -m "Build Tailwind CSS output" || echo "No changes to commit"
          git push origin HEAD
